import fs from 'fs/promises';
import path from 'path';

const LOGS_DIR = '/app/logs';
const WEBHOOK_URL = process.env.WEBHOOK_URL || '';
const MIN_SIGNIFICANCE = process.env.MIN_SIGNIFICANCE || 'low';

const SIGNIFICANCE_RANK = { low: 0, medium: 1, high: 2 };

export async function report(summaries) {
  const date = new Date().toISOString().split('T')[0];
  const filtered = summaries.filter((s) => meetsThreshold(s.summary?.significance));

  if (filtered.length === 0) {
    console.log('[reporter] No significant changes to report today.');
    return;
  }

  const markdown = buildMarkdown(filtered, date);
  await saveReport(markdown, date);

  if (WEBHOOK_URL) {
    await sendWebhook(filtered, date);
  }

  console.log(`[reporter] Report saved for ${date} — ${filtered.length} change(s) reported.`);
}

function meetsThreshold(significance) {
  const sig = (significance || '').toString().toLowerCase();
  if (!sig || sig === 'unknown') return true;
  const min = (MIN_SIGNIFICANCE || 'low').toString().toLowerCase();
  return (SIGNIFICANCE_RANK[sig] ?? 0) >= (SIGNIFICANCE_RANK[min] ?? 0);
}

function buildMarkdown(summaries, date) {
  const lines = [];

  lines.push(`Competitive Monitor Report — ${date}`);
  lines.push('');
  lines.push(`**${summaries.length} change(s) detected**`);
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const item of summaries) {
    const s = item.summary;
    const badge = significanceBadge(s?.significance);

    lines.push(`## ${item.competitor} — ${item.label} ${badge}`);
    lines.push(`>  ${item.url}`);
    lines.push(`>  Changes since: ${item.previousDate}`);
    lines.push('');

    if (s?.summary) {
      lines.push(`# Summary`);
      lines.push(s.summary);
      lines.push('');
    }

    if (s?.reasoning) {
      lines.push(`# Why it matters`);
      lines.push(s.reasoning);
      lines.push('');
    }

    if (s?.action_items?.length) {
      lines.push(`# Action items`);
      for (const action of s.action_items) {
        lines.push(`- ${action}`);
      }
      lines.push('');
    }

    lines.push(`<details><summary>Raw diff</summary>`);
    lines.push('');
    if (item.removedText) {
      lines.push('*Removed:*');
      lines.push('```');
      lines.push(item.removedText.slice(0, 500));
      lines.push('```');
    }
    if (item.addedText) {
      lines.push('*Added:*');
      lines.push('```');
      lines.push(item.addedText.slice(0, 500));
      lines.push('```');
    }
    lines.push('</details>');
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  lines.push(`*Generated by competitive-monitor at ${new Date().toISOString()}*`);
  return lines.join('\n');
}

function significanceBadge(significance) {
  const map = { low: '🟡', medium: '🟠', high: '🔴' };
  return map[significance] || '⚪';
}

async function saveReport(markdown, date) {
  const dir = path.join(LOGS_DIR, date);
  await fs.mkdir(dir, { recursive: true });
  const filepath = path.join(dir, 'report.md');
  await fs.writeFile(filepath, markdown);
  console.log(`[reporter] Markdown report → ${filepath}`);
}

async function sendWebhook(summaries, date) {
  const high = summaries.filter((s) => s.summary?.significance === 'high');
  const lines = [
    `🕵️ **Competitive Monitor — ${date}**`,
    `${summaries.length} change(s) detected${high.length ? ` | 🔴 ${high.length} HIGH significance` : ''}`,
    '',
    ...summaries.map(
      (s) =>
        `**${s.competitor} / ${s.label}** ${significanceBadge(s.summary?.significance)}\n${s.summary?.summary || 'No summary available.'}`
    ),
  ];

  try {
    const res = await fetch(WEBHOOK_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ content: lines.join('\n') }),
    });
    console.log(`[reporter] Webhook sent — status ${res.status}`);
  } catch (err) {
    console.error(`[reporter] Webhook failed: ${err.message}`);
  }
}