import fs from 'fs/promises';
import path from 'path';
import { buildReportPayload } from './report-data.js';

const LOGS_DIR = process.env.LOGS_DIR || path.join(process.cwd(), 'logs');
const WEBHOOK_URL = process.env.WEBHOOK_URL || '';

const FILLER = /see the full changelog|further details were not available/i;

export async function report(summaries) {
  const date = new Date().toISOString().split('T')[0];

  if (summaries.length === 0) {
    console.log('[reporter] No platforms to report today.');
    return;
  }

  const markdown = buildMarkdown(summaries, date);
  const payload = buildReportPayload(summaries, date);
  await saveReport(markdown, payload, date);

  if (WEBHOOK_URL) {
    await sendWebhook(summaries, date);
  }

  const updated = summaries.filter((s) => s.hasNewPatch && s.summary).length;
  const partial = summaries.filter((s) => s.summary?.quality === 'partial' || s.summary?.quality === 'failed').length;
  console.log(
    `[reporter] Report saved for ${date} — ${updated} new, ${summaries.length} total` +
      (partial ? `, ${partial} partial/failed` : '') +
      '.'
  );
}

function buildMarkdown(summaries, date) {
  const lines = [];

  lines.push(`# Patch Notes Digest — ${date}`);
  lines.push('');
  const newCount = summaries.filter((s) => s.hasNewPatch && s.summary).length;
  lines.push(`**${newCount} new patch(es) today** · **${summaries.length} platforms**`);
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const item of summaries) {
    lines.push(...formatPlatformSection(item));
    lines.push('---');
    lines.push('');
  }

  lines.push(`*Generated by patch-notes-monitor at ${new Date().toISOString()}*`);
  return lines.join('\n');
}

function formatPlatformSection(item) {
  const lines = [];
  const platform = item.platform || item.competitor;
  const s = item.summary || item.lastKnown?.summary;

  if (item.summaryError && !s) {
    lines.push(`## 📦 ${platform}`);
    lines.push('');
    lines.push(`⚠️ **Error:** ${item.summaryError}`);
    lines.push(`🔗 [Changelog](${item.url})`);
    lines.push('');
    return lines;
  }

  const status = item.hasNewPatch ? '🆕 **New patch today**' : '✅ **No update today**';
  const title = cleanTitle(s?.release_title);
  const badge = significanceBadge(s?.significance);

  lines.push(`## 📦 ${platform} ${badge}`);
  lines.push('');
  lines.push(`${status} · **Latest:** ${title}`);
  lines.push(`🔗 [View changelog](${item.url})`);
  lines.push('');

  if (s?.quality === 'partial') {
    lines.push(`> ⚠️ Partial summary — open the changelog for full details.`);
    lines.push('');
  }

  const sentences = pickSentences(s);
  if (sentences.length > 0) {
    lines.push('### Latest update');
    lines.push('');
    for (let i = 0; i < sentences.length; i++) {
      lines.push(`${i + 1}. ${sentences[i]}`);
    }
    lines.push('');
  } else if (item.summaryError) {
    lines.push(`⚠️ ${item.summaryError}`);
    lines.push('');
  }

  if (s?.significance) {
    const upgrade = s.upgrade_recommended ? ' · **Upgrade recommended**' : '';
    lines.push(`**Impact:** ${String(s.significance).toUpperCase()}${upgrade}`);
    lines.push('');
  }

  return lines;
}

function pickSentences(s) {
  if (!s) return [];

  return (s.sentences || [])
    .filter((d) => d && !FILLER.test(d) && d.length > 30)
    .slice(0, 3);
}

function cleanTitle(title) {
  if (!title || /^latest release$/i.test(title)) return 'See changelog';
  if (title.length > 70) return `${title.slice(0, 67)}...`;
  if (/firebase support|release notescopy|skip to main/i.test(title)) return 'See changelog';
  return title;
}

function significanceBadge(significance) {
  const map = { low: '🟡', medium: '🟠', high: '🔴' };
  return map[(significance || '').toLowerCase()] || '';
}

async function saveReport(markdown, payload, date) {
  const dir = path.join(LOGS_DIR, date);
  await fs.mkdir(dir, { recursive: true });
  const mdPath = path.join(dir, 'report.md');
  const jsonPath = path.join(dir, 'report.json');
  await fs.writeFile(mdPath, markdown);
  await fs.writeFile(jsonPath, JSON.stringify(payload, null, 2));
  console.log(`[reporter] Markdown report → ${mdPath}`);
  console.log(`[reporter] JSON report → ${jsonPath}`);
}

async function sendWebhook(summaries, date) {
  const blocks = summaries.map((item) => {
    const platform = item.platform || item.competitor;
    const s = item.summary || item.lastKnown?.summary;
    const sentences = pickSentences(s);
    const body = sentences.map((b) => `• ${b}`).join('\n') || 'No summary.';
    const tag = item.hasNewPatch ? 'NEW' : 'No update';
    return `📦 **${platform}** (${tag})\n${body}`;
  });

  try {
    await fetch(WEBHOOK_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        content: [`📋 **Patch Notes — ${date}**`, '', ...blocks].join('\n\n'),
      }),
    });
  } catch (err) {
    console.error(`[reporter] Webhook failed: ${err.message}`);
  }
}
