import http from 'http';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const UI_DIR = path.join(ROOT, 'ui');
const LOGS_DIR = process.env.LOGS_DIR || path.join(ROOT, 'logs');
const PORT = parseInt(process.env.UI_PORT || '3000', 10);

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
};

const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url || '/', `http://localhost:${PORT}`);

    if (url.pathname === '/api/dates') {
      return sendJson(res, await listDates());
    }

    if (url.pathname === '/api/latest') {
      const dates = await listDates();
      if (!dates.length) return sendJson(res, { error: 'No reports yet' }, 404);
      return sendJson(res, await loadReport(dates[0]));
    }

    const reportMatch = url.pathname.match(/^\/api\/report\/(\d{4}-\d{2}-\d{2})$/);
    if (reportMatch) {
      return sendJson(res, await loadReport(reportMatch[1]));
    }

    if (url.pathname === '/' || url.pathname === '/index.html') {
      return sendFile(res, path.join(UI_DIR, 'index.html'));
    }

    const asset = path.join(UI_DIR, url.pathname.replace(/^\/+/, ''));
    if (asset.startsWith(UI_DIR)) {
      try {
        await fs.access(asset);
        return sendFile(res, asset);
      } catch {
        /* fall through */
      }
    }

    sendJson(res, { error: 'Not found' }, 404);
  } catch (err) {
    console.error('[ui]', err);
    sendJson(res, { error: err.message }, 500);
  }
});

async function listDates() {
  try {
    const entries = await fs.readdir(LOGS_DIR, { withFileTypes: true });
    const dates = [];
    for (const entry of entries) {
      if (!entry.isDirectory() || entry.name === 'state') continue;
      const jsonPath = path.join(LOGS_DIR, entry.name, 'report.json');
      const mdPath = path.join(LOGS_DIR, entry.name, 'report.md');
      try {
        await fs.access(jsonPath);
        dates.push(entry.name);
      } catch {
        try {
          await fs.access(mdPath);
          dates.push(entry.name);
        } catch {
          /* skip */
        }
      }
    }
    return dates.sort((a, b) => b.localeCompare(a));
  } catch {
    return [];
  }
}

async function loadReport(date) {
  const jsonPath = path.join(LOGS_DIR, date, 'report.json');
  try {
    const raw = await fs.readFile(jsonPath, 'utf-8');
    return JSON.parse(raw);
  } catch {
    const mdPath = path.join(LOGS_DIR, date, 'report.md');
    try {
      const md = await fs.readFile(mdPath, 'utf-8');
      return parseMarkdownReport(md, date);
    } catch {
      return { error: `No report for ${date}` };
    }
  }
}

function parseMarkdownReport(md, date) {
  const platforms = [];
  const blocks = md.split(/^---$/m).filter((b) => b.includes('## 📦'));

  for (const block of blocks) {
    const nameMatch = block.match(/^## 📦\s+(.+?)(?:\s+[🟡🟠🔴])?\s*$/m);
    if (!nameMatch) continue;

    const platform = nameMatch[1].trim();
    const hasNew = /New patch today/.test(block);
    const latestMatch = block.match(/\*\*Latest:\*\*\s*(.+)/);
    const urlMatch = block.match(/\[View changelog\]\(([^)]+)\)/) || block.match(/\[Changelog\]\(([^)]+)\)/);
    const impactMatch = block.match(/\*\*Impact:\*\*\s*(\w+)/i);
    const errorMatch = block.match(/⚠️ \*\*Error:\*\*\s*(.+)/);

    const sentences = [];
    const updateSection = block.split('### Latest update')[1];
    if (updateSection) {
      for (const line of updateSection.split('\n')) {
        const m = line.match(/^\d+\.\s+(.+)/);
        if (m) sentences.push(m[1].trim());
      }
    }

    platforms.push({
      platform,
      label: '',
      url: urlMatch?.[1] || '',
      hasNewPatch: hasNew,
      status: hasNew ? 'new' : 'no_update',
      latestTitle: latestMatch?.[1]?.trim() || 'See changelog',
      releaseDate: '',
      significance: (impactMatch?.[1] || 'low').toLowerCase(),
      upgradeRecommended: /Upgrade recommended/.test(block),
      quality: /Partial summary/.test(block) ? 'partial' : errorMatch ? 'failed' : 'good',
      sentences,
      error: errorMatch?.[1]?.trim() || null,
    });
  }

  const header = md.match(/\*\*(\d+) new patch/);
  return {
    date,
    generatedAt: md.match(/Generated by .+ at (.+)\*/)?.[1] || null,
    newCount: parseInt(header?.[1] || '0', 10),
    platformCount: platforms.length,
    platforms,
    _source: 'markdown',
  };
}

function sendJson(res, data, status = 200) {
  res.writeHead(status, {
    'Content-Type': 'application/json; charset=utf-8',
    'Cache-Control': 'no-store',
  });
  res.end(JSON.stringify(data));
}

async function sendFile(res, filepath) {
  const ext = path.extname(filepath);
  const body = await fs.readFile(filepath);
  res.writeHead(200, { 'Content-Type': MIME[ext] || 'application/octet-stream' });
  res.end(body);
}

server.listen(PORT, () => {
  console.log(`[ui] Dashboard → http://localhost:${PORT}`);
  console.log(`[ui] Reading logs from ${LOGS_DIR}`);
});
